# Generated by Django 4.2.28 on 2026-02-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_instructor_course_thumbnail_course_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Public URL for course thumbnail image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='profile_pic_url',
            field=models.URLField(blank=True, help_text='Public URL for profile picture', max_length=500, null=True),
        ),
    ]
