name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: mooc_user
          POSTGRES_PASSWORD: mooc_password
          POSTGRES_DB: mooc_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      env:
        DATABASE_URL: postgres://mooc_user:mooc_password@localhost:5432/mooc_db
        SECRET_KEY: test-secret-key
        DEBUG: 'False'
      run: |
        python manage.py migrate

    - name: Run tests
      env:
        DATABASE_URL: postgres://mooc_user:mooc_password@localhost:5432/mooc_db
        SECRET_KEY: test-secret-key
        DEBUG: 'False'
      run: |
        python manage.py test

    - name: Check for missing migrations
      env:
        SECRET_KEY: test-secret-key
        DEBUG: 'True'
      run: |
        python manage.py makemigrations --check --dry-run

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: mooc-catalog:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
